language: php
php:
  - '5.6'
  - '5.5'
  - '5.4'
  - '5.3'
services:
  - mongodb

env:
  matrix:
    - TEST_PHP_ARGS="-q -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    - REPORT_EXIT_STATUS=1
    global:
      secure: JTCsHN6nxMmv585RUKWyjoLwHzw8ZoBmSpyPAa5cojjJ6sbFsUE2GpxdtYx7ESlOsOiwMsQLGZi6CIITQ4sqeQMZtFCaPNy/LF4EeHE1bU5CXrgbNSS+xEp84Xir9JkjYjFfYFXBLr/O6pk5+WAWxt3qo1AqWkCwBu2ipS2GIXQ=

before_install:
  - sudo pip install cpp-coveralls

before_script:
  - "./.travis.scripts/compile.sh"

notifications:
  email:
    - bjori@mongodb.com

script:
  - make test coverage

after_success:
  - coveralls --exclude lib --exclude tests
